### ISSUE TITLE
Add VolumeClaimTemplates for Cassandra

### ISSUE THREAD

**Issue by gregswift** [jaegertracing/jaeger-openshift#54]
I'm not sure what the best approach is to include this, because it needs to be variablized. Specifically `storageClassName` and `resources.requests.storage`. I added the following under the StatefulSet `spec`:

```
    volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: standard
          resources:
            requests:
              storage: 3Gi
      - metadata:
          name: logs
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: standard
          resources:
            requests:
              storage: 1Gi
```
